### ISSUE TITLE
Discrepancy in LOReL Sawyer Dataset Compose Task Results: Seeking Clarification on Reproduction Efforts

### ISSUE THREAD

**Issue by ZhifengWu7** [Liang-ZX/SkillDiffuser#2]
Hello, I'm trying to reproduce the Compose task results for the LOReL Sawyer Dataset. I've obtained success rates of 22.9% (with num_episodes=4) and 19.2% (with num_episodes=10), which are lower than the approximately 25.21% reported in the paper. Could you please explain why this might be happening? I've attached a screenshot of the results for num_episodes=4.
![image](https://github.com/user-attachments/assets/fe5f7cb1-d37b-4e52-8ddb-2c7f019dc524)

**Comment by Liang-ZX** [comment]
> Hello, I'm trying to reproduce the Compose task results for the LOReL Sawyer Dataset. I've obtained success rates of 22.9% (with num_episodes=4) and 19.2% (with num_episodes=10), which are lower than the approximately 25.21% reported in the paper. Could you please explain why this might be happening? I've attached a screenshot of the results for num_episodes=4. ![image](https://private-user-images.githubusercontent.com/166958489/366160602-fe5f7cb1-d37b-4e52-8ddb-2c7f019dc524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5OTkwMDYsIm5iZiI6MTcyNTk5ODcwNiwicGF0aCI6Ii8xNjY5NTg0ODkvMzY2MTYwNjAyLWZlNWY3Y2IxLWQzN2ItNGU1Mi04ZGRiLTJjN2YwMTlkYzUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQyMDA1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTg1NTkyZDEyYWQ5MTEwODQ4ZGE4ZTk0Y2NiN2FhOGNiOGVjYzJjNmNmYzgyODY1NWU1ZmM1YjRmY2Q0Yzg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UCfxZXkEw0pt-fl8WECPBL_OdfsduO3NZ-TgI7s1MG8)

The checkpoint uploaded is for fine-tuning. Here are three wandb records from the original composed task experiments.
<img width="1393" alt="image" src="https://github.com/user-attachments/assets/6b6c6310-887b-4a31-a726-c981d5a93f2a">

<img width="1382" alt="image" src="https://github.com/user-attachments/assets/e7a35ba7-96d9-423f-9972-9091167d5886">

<img width="1392" alt="image" src="https://github.com/user-attachments/assets/041cfecf-5ed4-4e0c-be19-fb09438d2d86">

**Comment by ZhifengWu7** [comment]
Thank you for sharing your findings. Could you please provide more details about the fine-tuning process for the checkpoint? Specifically, I'm interested in knowing which hyperparameters were primarily adjusted during fine-tuning.

**Comment by Liang-ZX** [comment]
> Thank you for sharing your findings. Could you please provide more details about the fine-tuning process for the checkpoint? Specifically, I'm interested in knowing which hyperparameters were primarily adjusted during fine-tuning.

It's just fine-tuning the model's weights not changing hyperparameters with lorel dataset, but use long-horizon tasks to choose the best checkpoint. Further question please send email at liangzx@connect.hku.hk

**Comment by Liang-ZX** [comment]
> Thank you for sharing your findings. Could you please provide more details about the fine-tuning process for the checkpoint? Specifically, I'm interested in knowing which hyperparameters were primarily adjusted during fine-tuning.

If you would like to just evaluate the model, you can try this [checkpoint](https://connecthkuhk-my.sharepoint.com/:f:/g/personal/liangzx_connect_hku_hk/EmEB4acmhyNAiD9lqTbTiNkBJc0siJGWur9sLHsB_JSP_A?e=m6i8B7) by using

```bash
python hrl/main_hot.py env=lorel_sawyer_obs method=traj_option dt.n_layer=1 dt.n_head=4 option_selector.option_transformer.n_layer=1 option_selector.option_transformer.n_head=4 option_selector.commitment_weight=0.1 option_selector.option_transformer.hidden_size=128 batch_size=256 seed=1 warmup_steps=5000 resume=True checkpoint_path=model_250.ckpt diffuser.loadpath=[state_400000.pt](http://state_400000.pt/)
```

And you may meet a misalignment when loading the checkpoint. You had better modify the self.embed_ln in dec_encoder.py to the following version. And please also modify the dimension of self.embed_ln in class initialization to `hidden_size + self.act_dim`.
![image](https://github.com/user-attachments/assets/35707bb4-30c2-4028-8282-47078e59492b)

**Comment by quark404** [comment]
请问假如我需要从0开始训练，我是不是不需要用checkpoint同时将resume设置为false

**Comment by capediemmmm** [comment]
> Thank you for sharing your findings. Could you please provide more details about the fine-tuning process for the checkpoint? Specifically, I'm interested in knowing which hyperparameters were primarily adjusted during fine-tuning.

Have you solved the finetuning problem? Could you please share the settings to reproduce the performance reported in the paper?
