### ISSUE TITLE
How many RAMs does the h5py2pkl.py need in Setup LOReL Dataset?

### ISSUE THREAD

**Issue by abcdsaltfish** [Liang-ZX/SkillDiffuser#3]
I follow the README.md and here's error when I was running h5py2pkl.py. 
```
sim actions
sim ims
Killed
```
No *.pkl file was generated. My RAM is 48 GB.

**Comment by Liang-ZX** [comment]
> I follow the README.md and here's error when I was running h5py2pkl.py.
> 
> ```
> sim actions
> sim ims
> Killed
> ```
> 
> No *.pkl file was generated. My RAM is 48 GB.

Hi, I'm not sure. But our server is 125 GB, which is enough. Thank you.
