### ISSUE TITLE
为什么 Diffuser 和 Checkpoint 使用不同的阶段？

### ISSUE THREAD

**Issue by MK-D-Luffy** [Liang-ZX/SkillDiffuser#4]
你好，我想请教一个问题，为什么 Diffuser 和 Checkpoint 没有使用相同阶段的模型文件？目前，Diffuser 使用的是 state_400000.pt，而 Checkpoint 使用的是 model_250.ckpt。这两者之间有什么具体的原因或考虑吗？希望能得到解答，谢谢！

**Comment by Liang-ZX** [comment]
> 你好，我想请教一个问题，为什么 Diffuser 和 Checkpoint 没有使用相同阶段的模型文件？目前，Diffuser 使用的是 state_400000.pt，而 Checkpoint 使用的是 model_250.ckpt。这两者之间有什么具体的原因或考虑吗？希望能得到解答，谢谢！

写代码时，两个优化器是分开写的，导致两个模型的step的定义不同，所以这俩写的不一样，最后使用时用的还是同一个时刻保存的两个checkpoint
